# Configuration file for vw_explorer.
# Use either full paths or the {VWE} variable to denote directories as otherwise the paths will be relative to the directory where the script is run from.
paths:
  data_dir: "{VWE}/example_data"                        # Directory to look for the log
  observation_dir: "{VWE}/example_data/observations"    # Directory containing FITS files
  guider_dir: "{VWE}/example_data/guider_frames"        # Directory containing guider files
  output_dir: "{VWE}/example_data"                      # Directory for saving results